# Generated by Django 5.1.1 on 2024-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='minimun_stock',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productos',
            name='minimum_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
